# Generated by Django 6.1 on 2026-08-20 02:50

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('during', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('party_size', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('held', 'Held'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.resource')),
            ],
            options={
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status', 'confirmed')), expressions=[('resource', '='), ('during', '&&')], name='exclude_overlapping_bookings')],
            },
        ),
    ]
