# Generated by Django 6.1 on 2026-09-07 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='business',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='bookings.business'),
            preserve_default=False,
        ),
    ]
